version: '3'

services:
  engine_service:
    build:
      context: ./engine_service
    container_name: engine_service

  data_service:
    build:
      context: ./data_service
    container_name: data_service

